# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Posts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Posts
  pod 'RxSwift', '~> 4.5'
  pod 'RxCocoa', '~> 4.5'

  target 'PostsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest', '~> 4.5'
  end
  
  target 'PostsAPIEndToEndTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PostsCacheIntegrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemotePostsLoaderWithLocalFallbackIntegrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
